### PR TITLE
Python decorator styling

### PR DESCRIPTION
**Pull request by shalabhc**
@kirbyfan64 - Do you mind trying this out? This fixes the issue with the entire decorator line being unstyled. Instead, the '@' and just the following word is styled using the 'preproc' style.

### CODE REVIEW

**Comment by nilnor** [comment]
Slightly related to this, it would be nice to create a "real" Python mode with a new lexer and everything. I could take a look at that later, but what would really help in that case is if someone could provide a good example file containing all kinds of Python syntax (such as the [example file](https://github.com/nilnor/howl/blob/master/bundles/ruby/misc/example.rb) for Ruby).

**Comment by kirbyfan64** [comment]
@nilnor You might want to try out the [pygments examplefiles](https://bitbucket.org/birkenfeld/pygments-main/src/tip/tests/examplefiles/). Only issue is that they have every language except Python (but that's probably more because the Python docs use pygments).

**Comment by kirbyfan64** [comment]
So...this looks like it *kind of* works. Only other issue is that decorators don't need to be at the beginning of a line. Consider:

```
def outer():
    @abc
    def inner(): pass
```

When they aren't at the beginning, they aren't colored.

**Comment by nilnor** [comment]
@kirbyfan64 Thanks for the tip. That seems to be more of collection of different files each containing some subset of the syntax though, still requiring manual work to compile into one example file, and not neccesarily complete either I'm guessing.

**Comment by shalabhc** [comment]
A proper Python mode is a better, but more time consuming, alternative.
For now, I've updated this PR to better handle indented decorators as well as dotted names.

**Comment by kirbyfan64** [comment]
This looks like it works perfectly! What are the chances of getting it merged in?

**Comment by nilnor** [comment]
Very high now that you've given feedback :)

+1 from me, merge at will if you're satisfied @shalabhc .

**Pull request merged**
